### ISSUE TITLE
ref attribute for subsubsections with Gerby is None instead of subsubsection numbering string

### ISSUE THREAD

**Issue by topological-modular-forms** [gerby-project/plastex#61]
Hello!

Following the instructions for the Stacks Project [here](https://gerby-project.github.io/stacks-instructions), but modifying the divisors.tex file to read

```
\section{Introduction}
\label{section-introduction}
\subsection{Introduction}
\label{subsection-introduction}
\subsubsection{Introduction}
\label{subsubsection-introduction}

\noindent
In this chapter we study some very basic questions related
```
instead of
```
\section{Introduction}
\label{section-introduction}

\noindent
In this chapter we study some very basic questions related  
````

and running `plastex --renderer=Gerby book.tex` I get the error
```
Traceback (most recent call last):
  File "/home/emily/.local/bin/plastex", line 142, in <module>
    main(sys.argv)
  File "/home/emily/.local/bin/plastex", line 119, in main
    Renderer().render(document)
  File "/home/emily/.local/lib/python3.6/site-packages/plasTeX/Renderers/Gerby/__init__.py", line 303, in render
    _Renderer.render(self, document)
  File "/home/emily/.local/lib/python3.6/site-packages/plasTeX/Renderers/PageTemplate/__init__.py", line 380, in render
    BaseRenderer.render(self, document)
  File "/home/emily/.local/lib/python3.6/site-packages/plasTeX/Renderers/__init__.py", line 416, in render
    self.cacheFilenames(document)
  File "/home/emily/.local/lib/python3.6/site-packages/plasTeX/Renderers/__init__.py", line 384, in cacheFilenames
    self.cacheFilenames(child)
  File "/home/emily/.local/lib/python3.6/site-packages/plasTeX/Renderers/__init__.py", line 384, in cacheFilenames
    self.cacheFilenames(child)
  File "/home/emily/.local/lib/python3.6/site-packages/plasTeX/Renderers/__init__.py", line 384, in cacheFilenames
    self.cacheFilenames(child)
  [Previous line repeated 3 more times]
  File "/home/emily/.local/lib/python3.6/site-packages/plasTeX/Renderers/__init__.py", line 382, in cacheFilenames
    node.filename
  File "/home/emily/.local/lib/python3.6/site-packages/plasTeX/Renderers/__init__.py", line 289, in filename
    override = str(self.filenameoverride)
  File "/home/emily/.local/lib/python3.6/site-packages/plasTeX/Renderers/Gerby/__init__.py", line 60, in filenameoverride
    return environment + "-" + self.ref + "-" + self.userdata["tag"] + "-" + self.id + ".tag"
TypeError: must be str, not NoneType
```
The problem seems to be that the `self.ref` attribute is None for subsubsections: adding the line
```
print(environment + "-" + self.ref + "-" + self.userdata["tag"] + "-" + self.id + ".tag")
```
just before
```
return environment + "-" + self.ref + "-" + self.userdata["tag"] + "-" + self.id + ".tag"
```
in `plasTeX/Renderers/Gerby/__init__.py` (line 60) prints
```
chapter-31-01WO-divisors-section-phantom.tag
section-31.1-01WP-divisors-section-introduction.tag
subsection-31.1.1-0H6Y-divisors-subsection-introduction.tag
```
before python throws a TypeError, and printing `self.ref` separately in this case shows that it is is `None` instead of `31.1.1.1` for the subsubsection tag.

Is there a quick patch or workaround for this?

**Comment by pbelmans** [comment]
I hadn't run into this bug yet, and it is confusing that the `.ref` attribute is just empty. This seems to be something in core plasTeX, rather than Gerby. But plasTeX has seen many good updates since the time Gerby forked it, and Gerby would need to be merged back into upstream to benefit from this.

**Comment by topological-modular-forms** [comment]
Thanks for the reply! I looked into the plastex source code and figured the problem came from `plastex/plasTeX/__init__.py`:
```
if self.counter:
    try: secnumdepth = self.config['document']['sec-num-depth']
    except: secnumdepth = 10
    if secnumdepth >= self.level or self.level > self.ENDSECTIONS_LEVEL:
        self.ref = self.ownerDocument.createElement('the' + self.counter).expand(tex)
        self.captionName = self.ownerDocument.createElement(self.counter + 'name').expand(tex)
```
It turns out one simply needs to run
```
plastex --renderer=Gerby --sec-num-depth 3 book.tex
```
instead of
```
plastex --renderer=Gerby book.tex
```
It was a very silly thing in the end!

Thanks again =)
